function GenerateSprintResultTableTwo(offset1, offset2) {
    return '<table class="tg">'
  + '<tr>'
  + '  <td class="label"><div class="block-cap">Team</div></td>'
  + '  <td class="label"><div class="block-num">Wurf</div></td>'
  + '  <td class="label"><div class="block-num">Satz 1</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV 1</div></td>'
  + '  <td class="label"><div class="block-num">Satz 2</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV 2</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV</div></td>'
  + '  <td class="free"></td>'
  + '  <td class="label"><div class="block-cap">Team</div></td>'
  + '  <td class="label"><div class="block-num">Wurf</div></td>'
  + '  <td class="label"><div class="block-num">Satz 1</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV 1</div></td>'
  + '  <td class="label"><div class="block-num">Satz 2</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV 2</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV</div></td>'
  + ' </tr>'
  + ' <tr>'
  + '  <td class="data"><div class="block-cap" id="spieler_' + offset1 + '_0"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="wurf_' + offset1 + '_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset1 + '_0_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_0_0"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset1 + '_1_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_1_0"></div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="sv_' + offset1 + '_0"></div></td>'
  + '  <td class="free"></td>'
  + '  <td class="data"><div class="block-cap" id="spieler_' + offset2 + '_0"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="wurf_' + offset2 + '_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset2 + '_0_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset2 + '_0_0"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_ '+ offset2 + '_1_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset2 + '_1_0"></div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="sv_' + offset2 + '_0"></div></td>'
  + ' </tr>'
  + ' <tr>'
  + '  <td class="data"><div class="block-cap" id="spieler_' + offset1 + '_1"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="wurf_' + offset1 + '_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset1 + '_0_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_0_1"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset1 + '_1_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_1_1"></div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="sv_' + offset1 + '_1"></div></td>'
  + '  <td class="free"></td>'
  + '  <td class="data"><div class="block-cap" id="spieler_' + offset2 + '_1"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="wurf_' + offset2 + '_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset2 + '_0_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset2 + '_0_1"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_ '+ offset2 + '_1_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset2 + '_1_1"></div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="sv_' + offset2 + '_1"></div></td>'
  + '</tr>'
  + '</table>'
    }

function GenerateSprintResultTable(offset1) {
    return '<table class="tg" align="center">'
  + '<tr>'
  + '  <td class="label"><div class="block-cap">Team</div></td>'
  + '  <td class="label"><div class="block-num">Wurf</div></td>'
  + '  <td class="label"><div class="block-num">Satz 1</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV 1</div></td>'
  + '  <td class="label"><div class="block-num">Satz 2</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV 2</div></td>'
  + '  <td class="label"><div class="block-num-sv">SV</div></td>'
  + ' </tr>'
  + ' <tr>'
  + '  <td class="data"><div class="block-cap" id="spieler_' + offset1 + '_0"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="wurf_' + offset1 + '_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset1 + '_0_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_0_0"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_'+ offset1 + '_1_0">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_1_0"></div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="sv_' + offset1 + '_0"></div></td>'
  + ' </tr>'
  + ' <tr>'
  + '  <td class="data"><div class="block-cap" id="spieler_' + offset1 + '_1"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="wurf_' + offset1 + '_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_' + offset1 + '_0_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_0_1"></div></td>'
  + '  <td class="data-num"><div class="block-num" id="satz_'+ offset1 + '_1_1">0</div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="satz_sv_' + offset1 + '_1_1"></div></td>'
  + '  <td class="data-num"><div class="block-num-sv" id="sv_' + offset1 + '_1"></div></td>'
  + '</tr>'
  + '</table>'
    }
